version: "3.9"

services:
  postgres-classroom:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${CLASSROOM_DB_NAME}
    volumes:
      - pg_classroom:/var/lib/postgresql/data
    networks: [infra_net]

  postgres-booking:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${BOOKING_DB_NAME}
    volumes:
      - pg_booking:/var/lib/postgresql/data
    networks: [infra_net]

  postgres-users:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${USERS_DB_NAME}
    volumes:
      - pg_users:/var/lib/postgresql/data
    networks: [infra_net]

  mongodb:
    image: mongo:7
    volumes:
      - mongo_data:/data/db
    networks: [infra_net]

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    networks: [infra_net]

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks: [infra_net]

  kafka:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://${INFRA_PRIVATE_IP}:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_NUM_PARTITIONS=1
    volumes:
      - kafka_data:/bitnami/kafka
    networks: [infra_net]

networks:
  infra_net:
    driver: bridge

volumes:
  pg_classroom:
  pg_booking:
  pg_users:
  mongo_data:
  redis_data:
  rabbitmq_data:
  kafka_data:
