version: "3.9"

services:
  api-gateway:
    image: augusto573/api-gateway:${IMAGE_TAG:-latest}
    ports:
      - "80:80"
    networks: [claresys_net]

  auth-service:
    image: augusto573/auth-service:${IMAGE_TAG:-latest}
    env_file: .env
    networks: [claresys_net]

  booking-command:
    image: augusto573/booking-command:${IMAGE_TAG:-latest}
    env_file: .env
    networks: [claresys_net]

  booking-query:
    image: augusto573/booking-query:${IMAGE_TAG:-latest}
    env_file: .env
    networks: [claresys_net]

  classroom-service:
    image: augusto573/classroom-service:${IMAGE_TAG:-latest}
    env_file: .env
    networks: [claresys_net]

  user-service:
    image: augusto573/user-service:${IMAGE_TAG:-latest}
    env_file: .env
    networks: [claresys_net]

  timetable-engine:
    image: augusto573/timetable-engine:${IMAGE_TAG:-latest}
    env_file: .env
    networks: [claresys_net]

  notification-service:
    image: augusto573/notification-service:${IMAGE_TAG:-latest}
    env_file: .env
    networks: [claresys_net]

  reporting-service:
    image: augusto573/reporting-service:${IMAGE_TAG:-latest}
    env_file: .env
    networks: [claresys_net]

  maintenance-service:
    image: augusto573/maintenance-service:${IMAGE_TAG:-latest}
    env_file: .env
    networks: [claresys_net]

  auditlog-service:
    image: augusto573/auditlog-service:${IMAGE_TAG:-latest}
    env_file: .env
    networks: [claresys_net]

networks:
  claresys_net:
    driver: bridge
