name: Build and Push Docker Images

on:
  push:
    branches: [ "features" ]
  workflow_dispatch:

env:
  DOCKER_HUB_USERNAME: ${{secrets.DOCKER_USERNAME}}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:

          - service: classroom-service
            context: .
            dockerfile: apps/classroom-service/Dockerfile
          
          - service: booking-command
            context: .
            dockerfile: apps/booking-command/Dockerfile
            
          - service: booking-query
            context: .
            dockerfile: apps/booking-query/Dockerfile
            
          - service: auth-service
            context: .
            dockerfile: apps/auth-service/Dockerfile
            
          - service: user-service
            context: .
            dockerfile: apps/user-service/Dockerfile
            
          - service: notification-service
            context: .
            dockerfile: apps/notification-service/Dockerfile
            
          - service: audit-log-service
            context: .
            dockerfile: apps/audit-log-service/Dockerfile

          - service: maintenance-service
            context: .
            dockerfile: apps/maintenance-service/Dockerfile
            
          - service: reporting-service
            context: .
            dockerfile: apps/reporting-service/Dockerfile

          - service: timetable-engine
            context: ./apps/timetable-engine
            dockerfile: ./apps/timetable-engine/Dockerfile
            
          - service: api-gateway
            context: ./apps/api-gateway
            dockerfile: ./apps/api-gateway/Dockerfile
          
          - service: mqtt-bridge
            context: ./apps/mqtt-bridge
            Dockerfile: ./apps/mqtt-bridge/Dockerfile
          
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build and push ${{matrix.service}}
        uses: docker/build-push-action@v5
        with:
          context: ${{matrix.context}}
          file: ${{matrix.dockerfile}}
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/${{matrix.service}}:latest